### ISSUE TITLE
vh-*

### ISSUE THREAD

**Issue by shinzui** [tachyons-css/tachyons-heights#5]
The [docs](http://tachyons.io/docs/table-of-styles/#principles) points the `.vh` rules such as`.vh-100` to this module but I can't find them defined here.

**Comment by mrmrs** [comment]
@shinzui There are a few modules lagging behind the main repo at the moment. Will hopefully be resolved soon.

**Comment by shinzui** [comment]
Ah! I didn't realize that they were developed independently. Isn't it a lot of work to keep them in sync?
